name: app_minimizer_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.24.7'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9

  app_minimizer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
