name: app_minimizer
description: A plugin can minimize app.
version: 1.0.0+4
repository: https://github.com/yohom/app_minimizer

environment:
  sdk: ">=3.5.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.codecity.flutter_app_minimizer
        pluginClass: FlutterAppMinimizerPlugin
      ios:
        pluginClass: FlutterAppMinimizerPlugin
