plugins {
    id 'com.android.library'
}

group = 'dev.codecity.flutter_app_minimizer'
version = '1.0-SNAPSHOT'

android {
    namespace = 'dev.codecity.flutter_app_minimizer'
    compileSdk = 35

    defaultConfig {
        minSdk = 21
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

repositories {
    google()
    mavenCentral()
}
